---
- name: Download latest version of Wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Uncompress wordpress.tar.gz
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes
  become: true

- name: Copy Wordpress config values
  template:
    src: templates/wp-config.php.j2
    dest: "{{ wordpress_installation_dir }}/wp-config.php"
  become: true

- name: Setup Apache2 to serve Wordpress
  template:
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  become: true
  notify:
    - restart apache2
