---
- hosts: all
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apache2
          - libapache2-mod-php5.6
          - php5.6
          - python-mysqldb
          - mysql-server-5.7
        state: latest
        update_cache: true
      become: yes

    - name: Create database
      mysql_db:
        name: wordpress
        login_user: root
        state: present
      become: true

    - name: Create database user
      mysql_user:
        name: wordpress
        login_user: root
        password: 12345
        priv: wordpress.*:ALL
        state: present
      become: true

    - name: Download latest version of Wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Uncompress wordpress.tar.gz
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
      become: true

    - name: Copy Wordpress config sample
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
      become: true
