---
- hosts: database
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: Install database dependencies
      apt:
        name:
          - mysql-server-5.7
          - python-mysqldb
        state: latest
        update_cache: true
      become: yes

    - name: Create database
      mysql_db:
        name: "{{ database_name }}"
        login_user: root
        state: present
      become: true

    - name: Create database user
      mysql_user:
        name: "{{ database_user }}"
        login_user: root
        password: 12345
        priv: "{{ database_name }}.*:ALL"
        host: "{{ item }}"
        state: present
      become: true
      with_items:
        - localhost
        - 127.0.0.1
        - "{{ wordpress_host }}"

    - name: Copy MySQL config file
      copy:
        src: files/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/
      become: true
      notify:
        - restart mysql

- hosts: wordpress
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: Install wordpress dependencies
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - libmcrypt-dev
          - php-ssh2
          - php7.2
          - php7.2-dev
          - php7.2-gd
          - php7.2-mysql
        state: latest
        update_cache: true
      become: yes

    - name: Install mcrypt wrapper for PHP
      pear:
        name: pecl/mcrypt
        state: present
      become: true

    - name: Download latest version of Wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Uncompress wordpress.tar.gz
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
      become: true

    - name: Copy Wordpress config sample
      copy:
        src: "{{ wordpress_installation_dir }}/wp-config-sample.php"
        dest: "{{ wordpress_installation_dir }}/wp-config.php"
        remote_src: yes
        force: no
      become: true

    - name: Change Wordpress config values
      replace:
        path: "{{ wordpress_installation_dir }}/wp-config.php"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.value }}"
      become: true
      with_items:
        - { regexp: database_name_here, value: "{{ database_name }}" }
        - { regexp: username_here, value: "{{ database_user }}" }
        - { regexp: password_here, value: "{{ database_password }}" }
        - { regexp: localhost, value: "{{ database_host }}" }

    - name: Copy Apache2 config file
      template:
        src: templates/000-default.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
      become: true
      notify:
        - restart apache2
