---
- hosts: all
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apache2
          - libapache2-mod-php5.6
          - php5.6
        state: latest
        update_cache: true
      become: yes
