---
- hosts: database
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: Install database dependencies
      apt:
        name:
          - mysql-server-5.7
          - python-mysqldb
        state: latest
        update_cache: true
      become: yes

    - name: Create database
      mysql_db:
        name: wordpress
        login_user: root
        state: present
      become: true

    - name: Create database user
      mysql_user:
        name: wordpress
        login_user: root
        password: 12345
        priv: wordpress.*:ALL
        host: "{{ item }}"
        state: present
      become: true
      with_items:
        - localhost
        - 127.0.0.1
        - 10.0.0.3

    - name: Copy MySQL config file
      copy:
        src: files/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/
      become: true
      notify:
        - restart mysql

- hosts: wordpress
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: Install wordpress dependencies
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - libmcrypt-dev
          - php-ssh2
          - php7.2
          - php7.2-dev
          - php7.2-gd
          - php7.2-mysql
        state: latest
        update_cache: true
      become: yes

    - name: Install mcrypt wrapper for PHP
      pear:
        name: pecl/mcrypt
        state: present
      become: true

    - name: Download latest version of Wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Uncompress wordpress.tar.gz
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
      become: true

    - name: Copy Wordpress config sample
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
        force: no
      become: true

    - name: Change Wordpress config values
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        replace: "{{ item.value }}"
      become: true
      with_items:
        - { regexp: database_name_here, value: wordpress }
        - { regexp: username_here, value: wordpress }
        - { regexp: password_here, value: 12345 }
        - { regexp: localhost, value: 10.0.0.4 }

    - name: Copy Apache2 config file
      copy:
        src: files/000-default.conf
        dest: /etc/apache2/sites-available/
      become: true
      notify:
        - restart apache2
