---
- hosts: all
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apache2
          - libapache2-mod-php5.6
          - php5.6
          - python-mysqldb
          - mysql-server-5.7
        state: latest
        update_cache: true
      become: yes

    - name: Create database
      mysql_db:
        name: wordpress
        login_user: root
        state: present
      become: true

    - name: Create database user
      mysql_user:
        name: wordpress
        login_user: root
        password: 12345
        priv: wordpress.*:ALL
        state: present
      become: true

    - name: Download latest version of Wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Uncompress wordpress.tar.gz
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
      become: true

    - name: Copy Wordpress config sample
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
        force: no
      become: true

    - name: Change Wordpress config values
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        replace: "{{ item.value }}"
      become: true
      with_items:
        - { regexp: database_name_here, value: wordpress }
        - { regexp: username_here, value: wordpress }
        - { regexp: password_here, value: 12345 }

    - name: Copy Apache2 config file
      copy:
        src: files/000-default.conf
        dest: /etc/apache2/sites-available/
      become: true
