Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "private_network", ip: "10.0.0.2"
    ansible.vm.provision "shell",
       inline: "apt-get update && apt-get install -y ansible"
    ansible.vm.provision "shell",
      inline: "cp /vagrant/configs/id_ed25519* /home/vagrant/.ssh/ && \
               chmod 600 /home/vagrant/.ssh/id_ed25519* && \
               chown vagrant:vagrant /home/vagrant/.ssh/id_ed25519*"
  end

  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.network "private_network", ip: "10.0.0.3"
    wordpress.vm.network "forwarded_port", guest: 80, host: 8080
    wordpress.vm.provision "shell",
      inline: "apt-get update && apt-get install -y python"
    wordpress.vm.provision "shell",
      inline: "cat /vagrant/configs/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys"
  end

  config.vm.define "database" do |database|
    database.vm.network "private_network", ip: "10.0.0.4"
    database.vm.provision "shell",
      inline: "apt-get update && apt-get install -y python"
    database.vm.provision "shell",
      inline: "cat /vagrant/configs/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys"
  end
end
